name: Dominic Monyoncho
url: http://daumie.github.io
description: Web Developer | Life Student
permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
